### ISSUE TITLE
The task showed up as . (dot) instead of checkbox

### ISSUE THREAD

**Issue by trungng2006** [larslockefeer/obsidian-plugin-todo#1]
Thank you for this plugin. However, when i try it out, the task in the pane show up as dot instead of checkbox.
![image](https://user-images.githubusercontent.com/71961905/108485444-e1fe3300-72d7-11eb-8c07-f55647aca99c.png)

**Comment by larslockefeer** [comment]
Hi @trungng2006, thanks for trying it out :) For me it works with an out-of-the-box installation of Obsidian. For me to understand the issue, can you share if you have a custom theme, custom CSS or other plugins added to your Obsidian installation?

**Comment by trungng2006** [comment]
You are correct. I tried on a new vault and the pane display correctly.
I think this is the problem with CSS rather than plugins. I disabled all plugins except for ToDo and the problem persisted.
Will try to probe around with the CSS and let you know

**Comment by trungng2006** [comment]
I found it:
```
input[type=checkbox] {
    -webkit-appearance: none;
    appearance: none;
    border-radius: 50%;
    border: 1px solid var(--text-faint);
    padding: 0;
}
```
When comment this out the box appear again

**Comment by mikeriss** [comment]
> I found it:
> 
> ```
> input[type=checkbox] {
>     -webkit-appearance: none;
>     appearance: none;
>     border-radius: 50%;
>     border: 1px solid var(--text-faint);
>     padding: 0;
> }
> ```
> 
> When comment this out the box appear again

I have the same issue. How do I comment out the CSS?

**Comment by trungng2006** [comment]
> I have the same issue. How do I comment out the CSS?
Try to locate that code in your obsidian.css or snippet.
Then you can delete that piece of code, or wrap the code in /*  and */

eg: 
```
/*
input[type=checkbox] {
    -webkit-appearance: none;
    appearance: none;
    border-radius: 50%;
    border: 1px solid var(--text-faint);
    padding: 0;
}
*/

**Comment by mikeriss** [comment]
Thanks, I can now see the checkbox. 
Although it doesnt have the feel and look of the minimal theme anymore

**Comment by larslockefeer** [comment]
@mikeriss & @trungng2006 are you both using the minimal theme?

**Comment by trungng2006** [comment]
I use gruvbox. But I copy this snippet from the minimal  theme.

**Comment by mikeriss** [comment]
My guess is that its not showing  a dot but instead its the actual checkbox but we are only seeing the a small portion of it. There could be too much padding. my two cents

**Comment by trungng2006** [comment]
> My guess is that its not showing a dot but instead its the actual checkbox but we are only seeing the a small portion of it. 
This is correct. Increasing the `px` in `border: 1px` does make the circle larger. But fails to show task done check mark when click.
I am willing to forgo the minimal checkbox for this great feature though. :D

**Comment by mikeriss** [comment]
I found the issue. 
In Minimal.css under input[type=checkbox] change the padding to 7px. Check the CSS below
![image](https://user-images.githubusercontent.com/5846456/108600635-6ca66700-7398-11eb-8f35-f9c824d8a750.png)

input[type=checkbox] {
  -webkit-appearance:none;
  appearance:none;
  border-radius:50%;
  border:2px solid var(--background-modifier-border-hover);
  padding:7px; 
}

**Comment by trungng2006** [comment]
Very nice! Thank you for letting me know!

**Comment by larslockefeer** [comment]
Thanks for diving into this! I'll try to reproduce with the Minimal theme enabled and see if I can prevent this from occurring with the out-of-the-box configuration of Minimal.
