### ISSUE TITLE
Option to divide Tasks by Note

### ISSUE THREAD

**Issue by frvkl** [larslockefeer/obsidian-plugin-todo#11]
Love the plugin. Using it every day. 

It would be great if there was a toggle for dividing the tasks per note in the pane, using the note title as seperator. Now I find myself clicking on the task to open the note, to find the context of the task. 

using the note title as optional divider, would give context to the task.

Hope I have explained it properly?

**Comment by benhummel** [comment]
+1, I would find this really useful!

**Comment by harmtemolder** [comment]
I’ve been trying my hand at this [here](https://github.com/harmtemolder/obsidian-plugin-todo/tree/group-by-file), but I had to jump through some hoops to get the right information available at the right time. I’m thinking to restructure the plugin. Maybe that’s what zsviczian is doing [here](https://github.com/zsviczian/Obsidian-GTD-plugin)?

**Comment by rui-nar** [comment]
why was this closed ?
I'm also very interested in having todos nested per filename ...
