### ISSUE TITLE
Use daily note format for dates e.g. [[2021-04-05]] instead of tags (#2021-04-05]]

### ISSUE THREAD

**Issue by waynemsmith** [larslockefeer/obsidian-plugin-todo#12]
Hi,

Great work here on this plugin.

I have created dedicated request for this feature that was mentioned [here](https://github.com/larslockefeer/obsidian-plugin-todo/issues/2#issuecomment-782251969).

This would unify the usage of dates, provide backlinks, reduce the clutter in tags and make entering of dates easier.

**Comment by dummifiedme** [comment]
Seconded. Also, the current format is YYYY-DD-MM, I would very much like to have YYYY-MM-DD. If its possible please implement it, even as an option. :)

**Comment by harmtemolder** [comment]
I use [[2021/2021-04/2021-04-05]] for daily notes, so would be good to read the setting from somewhere and implement this dynamically

**Comment by larslockefeer** [comment]
Hi @waynemsmith, thanks for the report. I have just merged some changes to main that add support for custom date formats, see #35 for a summary. With these changes, yYou could achieve what you are looking for by changing the newly introduced date tag format setting to `[[%date%]]`.

For now it's only possible to use this by installing the plugin from source. If you have some time to test-drive the changes, that would be great. I'm waiting for some confirmation to be sure that it works for everyone and not just for me. Once I get some confirmation, I'll cut a new release that includes the fix, such that all users can upgrade from within Obsidian.

**Comment by ryanmsnyder** [comment]
I haven't been able to get this feature to work. Does the plugin still need to be installed from source in order to gain the above functionality? I'm currently using the plugin installed from the community plugins installer. Here are my settings:

![SCR-20220516-ezd](https://user-images.githubusercontent.com/41448219/168642983-a3336107-d664-4cdd-9ac8-0377ce7cfab9.png)

**Comment by ryanmsnyder** [comment]
Disregard my comment. I found my issue was with the date format field.
