### ISSUE TITLE
Date format specified in README.md is incorrect

### ISSUE THREAD

**Issue by albert-kuo** [larslockefeer/obsidian-plugin-todo#22]
Currently the date format says this:

Schedule a TODO for a specific date by adding a tag #YYYY-**DD-MM**

But I think you meant this:

Schedule a TODO for a specific date by adding a tag #YYYY-**MM-DD**

**Comment by larslockefeer** [comment]
Hi @albert-kuo, thanks for your report. I have fixed this as part of #35.
