### ISSUE TITLE
Alternative date format

### ISSUE THREAD

**Issue by jramb** [larslockefeer/obsidian-plugin-todo#27]
It would be great if the date recognized could alternative have the format of a link to the date:
- [ ] One way #2021-05-07
- [ ] Another way [[2021-05-07]]
Would match great with "Natural Language Dates", which produces links.

**Comment by 23727** [comment]
This would be nice

**Comment by larslockefeer** [comment]
Hi all, thanks for chiming in on this issue!

I have just merged some changes to main that add support for custom date formats, see #35 for a summary. By installing this plugin directly from source, you should be able to use this. I'm waiting for some others to test-drive this to be sure that it works for everyone and not just for me. Once I get some confirmation, I'll cut a new release that includes the fix, such that all users can upgrade from within Obsidian.
