### ISSUE TITLE
Assume tasks in a daily note are scheduled for that day

### ISSUE THREAD

**Issue by dcoales** [larslockefeer/obsidian-plugin-todo#28]
Could the scheduled section show tasks in daily notes grouped by the date extracted from the daily note file name according to the date format specified in the daily note config.  I'm using the Slated plugin to move tasks from day to day and being able to see the overview without having to constantly juggle tags would be awesome.

Thanks.

**Comment by larslockefeer** [comment]
Hi @dcoales, thanks for your report and sorry for the delay 🙃  I have just pushed a new release which includes this feature.
