### ISSUE TITLE
Due Date Not Appearing

### ISSUE THREAD

**Issue by 23727** [larslockefeer/obsidian-plugin-todo#42]
Date tag format: [[%date%]]
Date format: yyyy-MM-dd

Test text:
- [ ] Test Replacement App: Last Pass [[2022-02-01]]

Output:
<img width="419" alt="Screen Shot 2021-12-29 at 17 43 27" src="https://user-images.githubusercontent.com/84650530/147715158-a1131698-9e18-4b6b-a17c-bc58146a2b3e.png">

Expected:
Sidebar displays task and due date as represented in the file

Is anyone else experiencing their due date being absent from the sidebar? 
Any fix or update?

Note: the default syntax also appears to result in an absent due date.

**Comment by larslockefeer** [comment]
Thanks for your report. An update that fixes this issue should be available soon.
