### ISSUE TITLE
Empty panel after the last update 

### ISSUE THREAD

**Issue by novobruna** [larslockefeer/obsidian-plugin-todo#45]
The plugin does not work anymore after the last update. This is what I see now in the Todo panel:

<img width="274" alt="Screenshot 2022-01-06 at 22 22 33" src="https://user-images.githubusercontent.com/34571816/148454006-1c35ed83-bcc4-4a19-b10e-c22785480884.png">

**Comment by larslockefeer** [comment]
Hey @novobruna, that's interesting 🤔 

- Can you screenshot an example of a file with a task?
- Can you go to View > Toggle developer tools and see if there's any errors in the Obsidian Developer Console?

**Comment by larslockefeer** [comment]
Would also be good to know:
- Which OS you are on
- Which version of Obsidian you are using

**Comment by novobruna** [comment]
Hi @larslockefeer, that was quick! :)

I'm using MAC OS 11.4 and Obsidian v0.13.19. Here you have a screenshot with the example task and the obsidian developer console:
<img width="1263" alt="Screenshot 2022-01-06 at 22 47 59" src="https://user-images.githubusercontent.com/34571816/148456779-880279dc-6baf-450b-a89d-27697ab08a6a.png">

**Comment by novobruna** [comment]
Hey @larslockefeer, I solved my issue. I had some old daily notes from Roam Research that were not following the standard naming convention (i.e., "January 6th, 2022" instead of "2022-01-06"). The error shown in the console disappeared after renaming those old notes.

**Comment by davebhc71** [comment]
Similar type of issue on Mobile.
iPadOS 15.2, Obsidian Mobile 1.05
![IMG_0494](https://user-images.githubusercontent.com/80698092/148545055-49df0236-2c71-411b-a837-2e1c308facd6.jpeg)

**Comment by larslockefeer** [comment]
Thanks for the report @novobruna and @davebhc71. I'll push a release that fixes this in a bit.

**Comment by davebhc71** [comment]
Thank you!

**Comment by davebhc71** [comment]
I would respectfully request that an Issue NOT be Closed until a fix is published/released as opposed to recognized. Thanks for your consideration.

**Comment by larslockefeer** [comment]
Hey @davebhc71, this should be fixed as of 0.2.5, released Friday. Do you still encounter the problem you reported?

**Comment by davebhc71** [comment]
Yes! Works great on Desktop. But not at all on iPadOS Mobile!

**Comment by davebhc71** [comment]
Still not working with latest update, v1.1, today (1/11/2022) to Mobile (iPadOS)

**Comment by davebhc71** [comment]
@larslockefeer, have you been able to confirm that it’s still an issue on Mobile?

**Comment by larslockefeer** [comment]
Hey @davebhc71, I found the issue and will push a new release in a bit.

**Comment by davebhc71** [comment]
What GOOD NEWS! This is the best plugin I use every day!!!

**Comment by davebhc71** [comment]
BINGO!!!!!!!! Works…Thanks so much!
