### ISSUE TITLE
Tasks without dates in daily notes now have a date

### ISSUE THREAD

**Issue by derfischmeister** [larslockefeer/obsidian-plugin-todo#47]
Since last update my Today tab is full of tasks. This is caused by the last update where the feature to support tasks in files inside the daily notes folder was implemented: [commit](https://github.com/larslockefeer/obsidian-plugin-todo/commit/679c4301e5d3fdc3c8f56a3aa1b69eb9734ca30e)

In my daily notes I often enter tasks with the #someday tag without a date. Because it's on the #someday list it doesn't need a date. This new update makes sure that when there is no date on a task, the date of the daily note will be copied. For me this is undesirable and I think more people will have the same workflow. Maybe the feature can be adjusted so that when the #someday tag is applied the date won't be copied from the daily note.

**Comment by larslockefeer** [comment]
Thanks for your report @derfischmeister. I'll push an update in a bit that fixes this.
