### ISSUE TITLE
#someday does not work on daily notes?

### ISSUE THREAD

**Issue by novobruna** [larslockefeer/obsidian-plugin-todo#48]
Hi, 

Apparently the tag someday does not work when used in a daily note?
<img width="1036" alt="Screenshot 2022-01-10 at 20 08 25" src="https://user-images.githubusercontent.com/34571816/148824547-66045e2b-0bf4-4ced-9217-7b2455ce1a6f.png">

I would expect *someday* to prevail and not the task scheduled for the day of the daily note. Does it make sense?

**Comment by larslockefeer** [comment]
Hey @novobruna, thanks for your report. I'll push an update in a bit that fixes this.
