### ISSUE TITLE
Different date formats cause different sorts

### ISSUE THREAD

**Issue by adamos486** [larslockefeer/obsidian-plugin-todo#5]
Love the concept of this plugin and will continue to use it! I did notice a few things though:

A tag `#2021-02-21` or even `#2021-02-22` will show up today. I noticed that your readme indicates a format of YYYY-DD-MM but your screenshot implies YYYY-MM-DD (which seems to be more accurate?).

A tag of `#2021-22-02` will show up as scheduled (I think because month 22 is larger than month 2?) as well as `#2021-03-01`. 

Here are my observations, and I'll keep digging in and look at source, but seems like "Today" may need more specificity.

**Comment by larslockefeer** [comment]
Hi @adamos486, thanks again for your report. I have been rather busy the last couple of months but have just now merged some changes to main that add support for custom date formats, see #35 for a summary.

By installing this plugin directly from source, you should be able to use this. I'm waiting for some others to test-drive this to be sure that it works for everyone and not just for me. Once I get some confirmation, I'll cut a new release that includes the fix, such that all users can upgrade from within Obsidian.
