### ISSUE TITLE
Bug report: due hint is not working

### ISSUE THREAD

**Issue by temirov** [larslockefeer/obsidian-plugin-todo#55]
The tasks with `[due:: yyyy-MM-dd]` don't go to the scheduled pane.

Obsidian version 0.13.23
Obsidian TODO version 0.2.7

Steps to reproduce:

1. Add the following line to any file
```
- [ ] Obsidian TODO plugin is awesome [due:: 2022-02-10]
````
2. Find the line in Inbox pane of the Obsidian TODO plugin

![Screen Shot 2022-02-06 at 10 38 52 PM](https://user-images.githubusercontent.com/1078274/152737579-a3de6774-3158-4bcf-b30f-4c904e60a0fe.png)

![Screen Shot 2022-02-06 at 10 42 07 PM](https://user-images.githubusercontent.com/1078274/152737913-182a5e6b-4fdf-4591-9c73-0da9c15335e9.png)

![Screen Shot 2022-02-06 at 10 45 29 PM](https://user-images.githubusercontent.com/1078274/152738237-03f40d36-8cd2-48f3-93c7-5179bfee960a.png)

![Screen Shot 2022-02-06 at 10 46 45 PM](https://user-images.githubusercontent.com/1078274/152738381-88b60ab3-b50e-49d0-8b9d-2007d0fb21a2.png)

**Comment by larslockefeer** [comment]
Hey @temirov, thanks for the report. With the standard settings of the plugin (as you shared in your screenshots), the format to use for due dates is different from what can be seen in the screenshots.

If you use the following format:

```
- [ ] Obsidian TODO plugin is awesome #2022-02-10
```

the tasks will end up in the scheduled pane as expected.

To make the format in the screenshots work, in the settings pane you could replace the `Date tag format` setting with the following:

```
[due:: %date%]
```

I'm sorry for the misleading screenshots. This has come up before, I'll replace them to match the standard settings.

**Comment by larslockefeer** [comment]
Updated the screenshots!
