### ISSUE TITLE
Failing on TriggerIndex | No rendering

### ISSUE THREAD

**Issue by chrisgmbishop** [larslockefeer/obsidian-plugin-todo#88]
Looks like there's an issue onLoad.
From what I can tell there is an error at TriggerIndex. Nothing is loading in the ToDo pane.

plugin:obsidian-plugin-todo:28
  | Promise.then (async) |   |  
-- | -- | -- | --
  | step | @ | plugin:obsidian-plugin-todo:29
  | eval | @ | plugin:obsidian-plugin-todo:30
  | __awaiter | @ | plugin:obsidian-plugin-todo:26
  | triggerIndex | @ | plugin:obsidian-plugin-todo:10054
  | eval | @ | plugin:obsidian-plugin-todo:10027
  | (anonymous) | @ | app.js:1
  | (anonymous) | @ | app.js:1
  | (anonymous) | @ | app.js:1
  | a | @ | app.js:1

Hopefully the above trace is helpful.

Thanks in advance!

**Comment by larslockefeer** [comment]
Hey @chrisgmbishop, I'm sorry to hear it is not working for you. I am not able to reproduce the issue locally unfortunately. Which version of Obsidian are you using? And can you maybe share a screenshot of the error in the Developer Console?

**Comment by chrisgmbishop** [comment]
Thanks for looking into this for me.

Oddly, the plugin is working on iPadOS and it looks awesome!

I'm using Obsidian on macOS v1.5.3

![Screenshot 2024-01-15 at 14 47 19](https://github.com/larslockefeer/obsidian-plugin-todo/assets/16527614/6cb931d6-fbd9-4966-a630-6189e4a46743)
![Screenshot 2024-01-15 at 14 47 35](https://github.com/larslockefeer/obsidian-plugin-todo/assets/16527614/295fb77d-a6b6-403b-8bcf-54297e1bcc06)

**Comment by chrisgmbishop** [comment]
@larslockefeer did that help?

**Comment by chrisgmbishop** [comment]
Everything seems to be rendering fine for me now.
Thanks!
