### ISSUE TITLE
Date format (like Slated plugin)

### ISSUE THREAD

**Issue by Gadwood** [larslockefeer/obsidian-plugin-todo#9]
Hello, it would be nice if the app use the same date system of the Slated plugin ( >20200319 ). This compatibility make many possibilities. I dont love to use tag to schedule thing because if i dont want to keep my tag result clean i need to remove them in my note.

**Comment by larslockefeer** [comment]
Hi @Gadwood, thanks for your report. I have just merged some changes to main that add support for custom date formats, see #35 for a summary.

By installing this plugin directly from source, you should be able to use this. I'm waiting for some others to test-drive this to be sure that it works for everyone and not just for me. Once I get some confirmation, I'll cut a new release that includes the fix, such that all users can upgrade from within Obsidian.
